### ISSUE TITLE
Ability to use TheTVDB api instead of TMDB

### ISSUE THREAD

**Issue by opentree27** [CollinHeist/TitleCardMaker#261]
**Describe the solution you'd like**
Ability to use the TheTVDB instead of TMDB for images. TheTVDB is generally a better source than TMDB. E.g. The recent southpark specials.

**Comment by CollinHeist** [comment]
I'd love to - the only reason I haven't done this yet is because TheTVDb API is paid, while TMDb's is free.

I should consider adding the *option* to use TVDb, but I have been trying to avoid spending money while developing the project. And I'd bet that only a very small subset of users would be willing to pay for their own API keys

**Comment by CollinHeist** [comment]
I'll close this for now. Developing support for a paid API that 99.9% of users won't use is not ideal, right now. Might implement this in the future, though!
