### ISSUE TITLE
Setup Issues - Samba shares with docker host

### ISSUE THREAD

**Issue by wheresaalto** [CollinHeist/TitleCardMaker#316]
### Installation

Docker - master tag

### Describe the Bug

Hello,

I'm trying to configure TCM in a docker container on my Debian server with sonarr, plex, and my video content stored on a separate Windows server.

I have my configuration working with "sync" up to the point of detecting all shows and creating all show title cards, but they fail to update in Plex. I'm also only able to run "sync" if I set episode_data_source to sonarr. So I think the issue is with my conenction to Plex.

The error I get when using Plex as episode_data_source is: [WARNING] Cannot source episodes for "[redacted] (US) (1998)" from plex.

When using sonarr as the episode_data_source, it makes it through all 18 hours of title card creation, but the "Updating Server" phase shows an enumeration of only 1 item for update, which doesn't align with the enumerations shown during "Creating cards" and "Selecting episodes".

Sample from log: Updating Server for "[redacted] (2017)":   0% 0/1 [00:00<?, ?it/s]

Do you know where I may have gone wrong?

Relevant log files and configuration files attached.

Thanks!
[Archive.zip](https://github.com/CollinHeist/TitleCardMaker/files/10951648/Archive.zip)

### Steps to reproduce the behavior

1. 
2.
...

### Debug Log

Log file included as attachment

**Comment by CollinHeist** [comment]
@wheresaalto There are a few things:

1. It is unnecessary (and doesn't do anything) to define a `card_directory` _and_ `volumes` map - `volumes` is only needed when you want to store the cards inside their respective media directories (so TCM can "convert" the Sonarr docker paths to TCM ones). Change your sync to this:
   ```yaml
   sync:
   - mode: match
     card_directory: /media/

   - file: /config/yaml/sonarr_sync_tv.yml
     add_template: tv_template
   ```
2. The reason TCM is not loading any cards into Plex is because none of your series have a `library` associated with them. Sonarr does not know your Plex libraries, and so TCM has to intuit them from your paths via the `plex_libraries` setting. This is described [here](https://github.com/CollinHeist/TitleCardMaker/wiki/YAML-Sync#plex-libraries). You will either want to add `library: TV Shows` to your template (which works so long as you are only ever syncing shows within that one library); or define the `plex_libraries` paths/libraries in your sync. If you change your sync make sure to delete the old file/series so TCM can remake them.

**Comment by wheresaalto** [comment]
Amazing, you fixed it right away.

Made both of the changes you recommended and it fixed it all right up.

Thanks!
