### ISSUE TITLE
Jellyfin sync original title as Kanji

### ISSUE THREAD

**Issue by Cwavs** [CollinHeist/TitleCardMaker#454]
**Is your feature request related to a problem? Please describe.**
Just set this up, and I noticed that the anime title has a kanji field to the populated which doesn't seem to get synced across from Jellyfin.

**Describe the solution you'd like**
Jellyfin stores the kanji for anime series and the like under the "original title" field in the series' metadata so that cards can use it.

**Describe alternatives you've considered**
I've considered adding these manually, however I have quite a few shows and I would not like to do this for all of them. I've also considered setting up Sonarr or TVDB to sync from there, but looking through the YAML sync docs, it's unclear whether this would actually sync that data.

**Additional context**
It might also be nice to generalise the kanji field in the card type into a more generic "alternative title" or "original language title" for other card types (where applicable) and also to allow it's use for other languages, eg Chinese or Korean series. (I'm guessing this is already possible to do, but I still feel changing the name to make this clearer would be nice).

**Comment by CollinHeist** [comment]
There is documentation on how you can add Kanji to the Anime card, see [here](https://github.com/CollinHeist/TitleCardMaker/wiki/AnimeTitleCard#adding-kanji) and [here](https://github.com/CollinHeist/TitleCardMaker/wiki/TMDb-Attributes#title-translation).

> Jellyfin stores the kanji for anime series and the like under the "original title" field in the series' metadata so that cards can use it.

Oh interesting, that's good to know, however TCM can pull that data from TMDb directly. I'll keep it this way since the TMDb integration already exists and is more widely applicable since a majority of users do not use Jellyfin

> I've also considered setting up Sonarr or TVDB to sync from there, but looking through the YAML sync docs, it's unclear whether this would actually sync that data.

You might be conflating some terms here - in TCM a `sync` is what adds series to a YAML file automatically, and where you Sync from is totally unrelated to adding translations. You can sync from anywhere and add those titles through the `translation` feature I mentioned earlier.

> It might also be nice to generalise the kanji field in the card type into a more generic "alternative title" or "original language title" for other card types (where applicable) and also to allow it's use for other languages, eg Chinese or Korean series. (I'm guessing this is already possible to do, but I still feel changing the name to make this clearer would be nice).

Like you said, the `kanji` field is just a label, you can put anything you want there. However >99% (probably 100% but who knows, haha) of users put the Japanese titles there, so I don't want to add confusion by renaming that.  If you want to use that field for other languages that's totally fine, however you might run into problems because the font used primarily has a Japanese character set, so Mandarin and Korean might not work.
